# Generated by Django 5.0.2 on 2024-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_remove_opcao_votos_opcao_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraProibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=200)),
            ],
        ),
    ]
